Repository PrestaShop/open-source, pull requests merged in 2023-11, with the labels that each got.

#226 QA : How to manage Issues
  content/project-organization/quality-council/processes/issue-management.md
Labels: waiting for author, Waiting for QA

#229 PR Management documentation
  content/project-organization/quality-council/processes/images/readme10.png
  content/project-organization/quality-council/processes/images/readme11.png
  content/project-organization/quality-council/processes/images/readme12.png
  content/project-organization/quality-council/processes/images/readme13.png
  content/project-organization/quality-council/processes/images/readme14.png
  content/project-organization/quality-council/processes/images/readme15.png
  content/project-organization/quality-council/processes/images/readme16.png
  content/project-organization/quality-council/processes/images/readme17.png
  content/project-organization/quality-council/processes/images/readme18.png
  content/project-organization/quality-council/processes/images/readme19.png
  content/project-organization/quality-council/processes/images/readme20.png
  content/project-organization/quality-council/processes/images/readme21.png
  content/project-organization/quality-council/processes/images/readme7.png
  content/project-organization/quality-council/processes/images/readme8.png
  content/project-organization/quality-council/processes/images/readme9.png
  content/project-organization/quality-council/processes/pr-management.md
Labels: waiting for author

#228 Add Release manager
  content/project-organization/quality-council/processes/_index.md
  content/project-organization/quality-council/processes/images/release_manager_img_1.png
  content/project-organization/quality-council/processes/images/release_manager_img_19.png
  content/project-organization/quality-council/processes/images/release_manager_img_2.png
  content/project-organization/quality-council/processes/images/release_manager_img_20.png
  content/project-organization/quality-council/processes/images/release_manager_img_21.png
  content/project-organization/quality-council/processes/images/release_manager_img_3.png
  content/project-organization/quality-council/processes/images/release_manager_img_4.png
  content/project-organization/quality-council/processes/release-manager.md
Labels: waiting for author

#232 Add ShaiMagal to committers
  content/project-organization/people-and-roles.md
Labels: Waiting for QA

#236 QA : Tooling (Test Scenarios)
  content/project-organization/quality-council/tooling/_index.md
  content/project-organization/quality-council/tooling/images/test-scenarios-github-project.png
  content/project-organization/quality-council/tooling/images/test-scenarios-hugo.png
  content/project-organization/quality-council/tooling/images/test-scenarios-xray.png
  content/project-organization/quality-council/tooling/nightly-board.md
  content/project-organization/quality-council/tooling/presthubot.md
  content/project-organization/quality-council/tooling/test-scenarios.md
Labels: waiting for author, Waiting for QA
